/*
 * Copyright 2025, Johan Wagenheim <johan@dospuntos.no>
 * All rights reserved. Distributed under the terms of the MIT license.
 */
#ifndef CONSTANTS_H
#define CONSTANTS_H

extern const char* kApplicationSignature;
extern const char* kApplicationName;

enum {
	M_TRANSFORM_UPPERCASE = 'UPCS',
	M_TRANSFORM_LOWERCASE,
	M_TRANSFORM_CAPITALIZE,
	M_TRANSFORM_TITLE_CASE,
	M_TRANSFORM_RANDOM_CASE,
	M_TRANSFORM_ALTERNATING_CASE,
	M_TRANSFORM_TOGGLE_CASE,
	M_REMOVE_LINE_BREAKS,
	M_INSERT_LINE_BREAKS,
	M_BREAK_LINES_ON_DELIMITER,
	M_TRIM_LINES,
	M_TRIM_EMPTY_LINES,
	M_TRANSFORM_ENCODE_URL,
	M_TRANSFORM_DECODE_URL,
	M_TRANSFORM_ENCODE_BASE64,
	M_TRANSFORM_DECODE_BASE64,
	M_TRANSFORM_ROT13,
	M_TRANSFORM_WIP,
	M_TRANSFORM_PREFIX_SUFFIX,
	M_TRANSFORM_REPLACE,
	B_TEXT_CHANGED,
	B_CURSOR_MOVED,
	M_INSERT_EXAMPLE_TEXT,
	M_UPDATE_STATUSBAR,
	M_FILE_NEW,
	M_FILE_OPEN,
	M_FILE_SAVE,
	M_FILE_SAVE_AS,
	M_TOGGLE_WORD_WRAP,
	M_MODE_REPLACE,
	M_MODE_BREAK,
	M_MODE_CHARACTERS
};

#endif // CONSTANTS_H
